
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: newmodel
    description: "A starter dbt model"
    columns:
      - name: PersonID
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
