# example profiles.yml file
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: dbtdb.database.windows.net
      port: 1433
      database: dbtdb
      schema: dbt_winnerpio
      authentication: ActiveDirectoryPassword
      user: ${dbuser}
      password: ${dbpass}