# example profiles.yml file
dbt_new:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: dbtdb.database.windows.net
      port: 1433
      database: dbtdb
      schema: dimensional
      authentication: ActiveDirectoryPassword
      user: "{{ env_var('dbuser') }}"
      password: "{{ env_var('dbpass') }}"